server:
  port: 9091

spring:
  config:
    import: "optional:configserver:"
  application:
    name: helloworld
  cloud:
    config:
      uri: http://localhost:8888
  # 설정하지 않으면 default profile
  profiles:
    active:
    - dev

management:
  endpoints:
    web:
      exposure:
        include: '*'